
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 01 12:17:56 GMT 2009
//----------------------------------------------------

package uk.ac.ed.inf.pepa.parsing.internal;

import java_cup.runtime.ComplexSymbolFactory.ComplexSymbol;
import java_cup.runtime.Symbol;
import java_cup.runtime.lr_parser;
import java.util.*;
import uk.ac.ed.inf.pepa.parsing.*;
import org.apache.log4j.Logger;
import uk.ac.ed.inf.pepa.analysis.*;
import uk.ac.ed.inf.pepa.analysis.internal.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Nov 01 12:17:56 GMT 2009
  */
public class PepaParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public PepaParser() {super();}

  /** Constructor which sets the default scanner. */
  public PepaParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public PepaParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\063\000\002\002\004\000\002\002\005\000\002\023" +
    "\004\000\002\023\002\000\002\027\004\000\002\027\002" +
    "\000\002\020\003\000\002\020\003\000\002\022\004\000" +
    "\002\022\003\000\002\021\006\000\002\021\004\000\002" +
    "\026\004\000\002\026\003\000\002\025\006\000\002\016" +
    "\007\000\002\011\003\000\002\011\003\000\002\013\005" +
    "\000\002\013\005\000\002\013\005\000\002\013\005\000" +
    "\002\013\005\000\002\013\003\000\002\013\003\000\002" +
    "\013\003\000\002\010\003\000\002\012\005\000\002\012" +
    "\003\000\002\003\005\000\002\003\005\000\002\003\003" +
    "\000\002\003\003\000\002\003\005\000\002\003\005\000" +
    "\002\003\003\000\002\003\003\000\002\007\006\000\002" +
    "\004\003\000\002\004\003\000\002\006\007\000\002\005" +
    "\005\000\002\017\005\000\002\017\003\000\002\024\005" +
    "\000\002\024\003\000\002\024\002\000\002\015\003\000" +
    "\002\015\003\000\002\014\003\000\002\014\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\131\000\020\003\ufffe\007\ufffe\024\ufffe\025\ufffe\034" +
    "\ufffe\035\ufffe\036\ufffe\001\002\000\020\003\010\007\ufffc" +
    "\024\ufffc\025\015\034\013\035\ufffc\036\ufffc\001\002\000" +
    "\004\002\006\001\002\000\004\002\001\001\002\000\020" +
    "\003\ufff8\007\ufff8\024\ufff8\025\ufff8\034\ufff8\035\ufff8\036" +
    "\ufff8\001\002\000\004\011\133\001\002\000\006\012\126" +
    "\014\130\001\002\000\020\003\uffff\007\uffff\024\uffff\025" +
    "\uffff\034\uffff\035\uffff\036\uffff\001\002\000\024\010\uffe7" +
    "\011\uffe7\012\uffe7\014\uffe7\020\uffe7\021\uffe7\022\uffe7\023" +
    "\uffe7\031\uffe7\001\002\000\012\007\032\024\023\035\024" +
    "\036\025\001\002\000\006\003\010\034\013\001\002\000" +
    "\020\003\ufff9\007\ufff9\024\ufff9\025\ufff9\034\ufff9\035\ufff9" +
    "\036\ufff9\001\002\000\020\002\uffe1\010\uffe1\011\uffe1\013" +
    "\uffe1\016\uffe1\022\uffe1\023\uffe1\001\002\000\014\002\000" +
    "\013\077\016\100\022\075\023\101\001\002\000\020\002" +
    "\uffdd\010\uffdd\011\uffdd\013\uffdd\016\uffdd\022\uffdd\023\uffdd" +
    "\001\002\000\004\005\124\001\002\000\006\035\024\036" +
    "\025\001\002\000\024\002\uffdb\010\uffdb\011\uffdb\012\uffdb" +
    "\013\uffdb\016\uffdb\022\uffdb\023\uffdb\030\uffdb\001\002\000" +
    "\024\002\uffda\010\uffda\011\uffda\012\uffda\013\uffda\016\uffda" +
    "\022\uffda\023\uffda\030\uffda\001\002\000\012\007\ufffd\024" +
    "\ufffd\035\ufffd\036\ufffd\001\002\000\020\002\uffe2\010\uffe2" +
    "\011\uffe2\013\uffe2\016\uffe2\022\uffe2\023\uffe2\001\002\000" +
    "\012\007\ufff4\024\ufff4\035\ufff4\036\ufff4\001\002\000\020" +
    "\002\uffde\012\117\013\uffde\016\uffde\022\uffde\023\uffde\030" +
    "\042\001\002\000\014\007\032\032\041\034\035\035\024" +
    "\036\036\001\002\000\014\010\076\013\077\016\100\022" +
    "\075\023\101\001\002\000\004\004\063\001\002\000\006" +
    "\004\uffd2\017\uffd2\001\002\000\020\004\uffd1\010\uffda\013" +
    "\uffda\016\uffda\022\uffda\023\uffda\030\uffda\001\002\000\022" +
    "\002\uffde\010\uffde\011\uffde\013\uffde\016\uffde\022\uffde\023" +
    "\uffde\030\042\001\002\000\004\004\uffd0\001\002\000\004" +
    "\004\uffcf\001\002\000\012\007\047\033\046\034\013\037" +
    "\045\001\002\000\020\010\uffe8\011\uffe8\020\uffe8\021\uffe8" +
    "\022\uffe8\023\uffe8\031\uffe8\001\002\000\014\020\054\021" +
    "\052\022\053\023\055\031\062\001\002\000\020\010\uffea" +
    "\011\uffea\020\uffea\021\uffea\022\uffea\023\uffea\031\uffea\001" +
    "\002\000\020\010\uffe9\011\uffe9\020\uffe9\021\uffe9\022\uffe9" +
    "\023\uffe9\031\uffe9\001\002\000\012\007\047\033\046\034" +
    "\013\037\045\001\002\000\014\010\051\020\054\021\052" +
    "\022\053\023\055\001\002\000\020\010\uffeb\011\uffeb\020" +
    "\uffeb\021\uffeb\022\uffeb\023\uffeb\031\uffeb\001\002\000\012" +
    "\007\047\033\046\034\013\037\045\001\002\000\012\007" +
    "\047\033\046\034\013\037\045\001\002\000\012\007\047" +
    "\033\046\034\013\037\045\001\002\000\012\007\047\033" +
    "\046\034\013\037\045\001\002\000\020\010\uffec\011\uffec" +
    "\020\uffec\021\uffec\022\uffec\023\uffec\031\uffec\001\002\000" +
    "\020\010\uffee\011\uffee\020\uffee\021\052\022\uffee\023\055" +
    "\031\uffee\001\002\000\020\010\uffef\011\uffef\020\uffef\021" +
    "\052\022\uffef\023\055\031\uffef\001\002\000\020\010\uffed" +
    "\011\uffed\020\uffed\021\uffed\022\uffed\023\uffed\031\uffed\001" +
    "\002\000\020\002\uffdc\010\uffdc\011\uffdc\013\uffdc\016\uffdc" +
    "\022\uffdc\023\uffdc\001\002\000\014\006\066\007\047\033" +
    "\064\034\013\037\045\001\002\000\014\010\uffe9\020\uffe9" +
    "\021\072\022\uffe9\023\uffe9\001\002\000\004\010\ufff0\001" +
    "\002\000\004\010\uffe5\001\002\000\014\010\ufff1\020\054" +
    "\021\052\022\053\023\055\001\002\000\004\010\071\001" +
    "\002\000\004\005\ufff2\001\002\000\004\006\073\001\002" +
    "\000\004\010\uffe6\001\002\000\010\007\032\035\024\036" +
    "\025\001\002\000\010\007\032\035\024\036\025\001\002" +
    "\000\020\002\uffdf\010\uffdf\011\uffdf\013\uffdf\016\uffdf\022" +
    "\uffdf\023\uffdf\001\002\000\026\002\uffd6\007\uffd6\010\uffd6" +
    "\011\uffd6\013\uffd6\016\uffd6\022\uffd6\023\uffd6\035\uffd6\036" +
    "\uffd6\001\002\000\014\004\uffd3\017\uffd3\021\112\034\035" +
    "\036\105\001\002\000\006\013\077\016\103\001\002\000" +
    "\020\002\uffe0\010\uffe0\011\uffe0\013\uffe0\016\uffe0\022\uffe0" +
    "\023\uffe0\001\002\000\012\004\uffd3\017\uffd3\034\035\036" +
    "\105\001\002\000\006\004\107\017\110\001\002\000\006" +
    "\004\uffd1\017\uffd1\001\002\000\006\004\uffd4\017\uffd4\001" +
    "\002\000\006\034\035\036\105\001\002\000\026\002\uffd7" +
    "\007\uffd7\010\uffd7\011\uffd7\013\uffd7\016\uffd7\022\uffd7\023" +
    "\uffd7\035\uffd7\036\uffd7\001\002\000\006\004\uffd5\017\uffd5" +
    "\001\002\000\004\017\113\001\002\000\010\007\032\035" +
    "\024\036\025\001\002\000\020\002\uffd9\010\uffd9\011\uffd9" +
    "\013\077\016\100\022\075\023\101\001\002\000\020\002" +
    "\uffe3\010\uffe3\011\uffe3\013\077\016\100\022\uffe3\023\101" +
    "\001\002\000\020\002\uffd8\010\uffd8\011\uffd8\013\uffd8\016" +
    "\uffd8\022\uffd8\023\101\001\002\000\010\007\032\035\024" +
    "\036\025\001\002\000\014\011\121\013\077\016\100\022" +
    "\075\023\101\001\002\000\012\007\ufff3\024\ufff3\035\ufff3" +
    "\036\ufff3\001\002\000\004\012\117\001\002\000\012\007" +
    "\ufff5\024\ufff5\035\ufff5\036\ufff5\001\002\000\010\007\032" +
    "\035\024\036\025\001\002\000\020\002\uffe4\010\uffe4\011" +
    "\uffe4\013\uffe4\016\uffe4\022\uffe4\023\101\001\002\000\012" +
    "\007\ufffa\033\ufffa\034\ufffa\037\ufffa\001\002\000\012\007" +
    "\047\033\046\034\013\037\045\001\002\000\012\007\ufffb" +
    "\033\ufffb\034\ufffb\037\ufffb\001\002\000\014\011\132\020" +
    "\054\021\052\022\053\023\055\001\002\000\020\003\ufff7" +
    "\007\ufff7\024\ufff7\025\ufff7\034\ufff7\035\ufff7\036\ufff7\001" +
    "\002\000\020\003\ufff6\007\ufff6\024\ufff6\025\ufff6\034\ufff6" +
    "\035\ufff6\036\ufff6\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\131\000\006\002\004\023\003\001\001\000\012\010" +
    "\010\021\006\022\011\027\013\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\020\126\001\001\000\002\001\001\000\002\001\001" +
    "\000\022\003\017\004\030\005\016\006\026\007\020\016" +
    "\021\025\027\026\025\001\001\000\006\010\010\021\015" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\017" +
    "\073\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\004\121\025\122\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\022\003\032\004\036\005\016\006" +
    "\026\007\020\014\033\015\037\016\021\001\001\000\004" +
    "\017\073\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\010\042\013\043\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\010\042\013\047\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\010\042\013\060\001\001\000\006" +
    "\010\042\013\057\001\001\000\006\010\042\013\056\001" +
    "\001\000\006\010\042\013\055\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\010\042\011\067\012\064\013\066" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\016\003\115\004" +
    "\036\005\016\006\026\007\020\016\021\001\001\000\016" +
    "\003\114\004\036\005\016\006\026\007\020\016\021\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\015\105" +
    "\024\103\001\001\000\004\017\101\001\001\000\002\001" +
    "\001\000\006\015\105\024\103\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\015\110\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\016\003\113\004\036\005\016\006\026\007\020\016" +
    "\021\001\001\000\004\017\073\001\001\000\004\017\073" +
    "\001\001\000\004\017\073\001\001\000\016\003\117\004" +
    "\036\005\016\006\026\007\020\016\021\001\001\000\004" +
    "\017\073\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\016\003\124\004\036\005\016\006\026" +
    "\007\020\016\021\001\001\000\004\017\073\001\001\000" +
    "\002\001\001\000\006\010\042\013\130\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$PepaParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$PepaParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$PepaParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



        
    static final Logger logger = Logger.getLogger("uk.ac.ed.inf.pepa.parsing.parser");
    
    private ParserException parserException = null; 
    
    private ArrayList<IProblem> parserProblems = new ArrayList<IProblem>();
	
    public void errorRecovered() {
    	IProblem syntaxError = ProblemFactory.createProblem(
			IProblem.SyntaxError, parserException.getLine(), 
			parserException.getColumn(),
			IProblem.POSITION_UNKNOWN, IProblem.POSITION_UNKNOWN, 
			parserException.getChar(), 
			parserException.getLength(), 
			parserException.getMessage());
		
		logger.debug("Error added");
		parserProblems.add(syntaxError);
			              	 	
    }
    
    public java_cup.runtime.Symbol parse() throws Exception {
    	Symbol result = null;
    	try {
    		result = super.parse();
    		ModelNode modelNode = action_obj.model;
    		modelNode.setProblems(parserProblems.toArray(
    			new IProblem[parserProblems.size()]));
    		if (result != null)
    			result.value = modelNode;
    	
    	} catch (Exception e) {
    		e.printStackTrace();
    		this.logger.debug("Exception occurred: " + e);
    	}
    	return result;
    	
    }    
    
    /* Return terminal symbols by sym. */	
	public String gettokenstr( int sym )
	{
	    String str;
	    switch( sym )
	    {	
	    	 case PepaToken.PASSIVE_MULTIPLIER: { str = " natural "; break; } 
	         case PepaToken.PROCESS_STRN:   { str=" identifier "; break; }
                 case PepaToken.ACTIVITY_STRN:  { str=" identifier "; break; }
                 case PepaToken.RPAREN:         { str=" ) "; break; }
             case PepaToken.TAU:				{ str=" TAU "; break; }
	         case PepaToken.SEMI:           { str=" ; "; break; }
	         case PepaToken.SUM:            { str=" + "; break; }
	         case PepaToken.LPAREN:         { str=" ( "; break; }
	         case PepaToken.HASH:           { str=" # "; break; }
	         case PepaToken.DOUBLE_NUMBER:  { str=" double "; break; }
	         case PepaToken.RCOOP:          { str=" > "; break; }
	         case PepaToken.EQUALS:         { str=" = "; break; }
	         case PepaToken.COMMA:  { str=" , "; break; }
	         case PepaToken.PERC:   { str=" % "; break; }
	         case PepaToken.EOF:    { str=" EOF "; break; }
	         case PepaToken.MULT:   { str=" * "; break; }
	         case PepaToken.DIVIDE: { str=" / "; break; }
	         case PepaToken.PAR:    { str=" || "; break; }
	         case PepaToken.TOP:    { str=" T or infty "; break; }
	         case PepaToken.MINUS:  { str=" - "; break; }
	         case PepaToken.DOT:    { str=" . "; break; }
	         case PepaToken.LCOOP:  { str=" < "; break; }
	         case PepaToken.RSET:   { str=" } "; break; }
	         case PepaToken.COOP:   { str=" <> "; break;}
	         case PepaToken.LSET:   { str=" { "; break; }	
	         case PepaToken.LSQUARE:{ str=" [ "; break; }
	         case PepaToken.RSQUARE:{ str=" ] "; break; }
		 case PepaToken.QUOTED_STRN:{str=" Quoted string";break;}
             case PepaToken.RATE_EQUALS: 
                                    { str=" := "; break; }
             default: str="";
	   }
	   return str;      
	}
	
	public Symbol getCurrentToken() {
		return this.cur_token;
	}
	
	public java.util.Stack getStack() {
		return stack;
	}
	
	public void syntax_error(java_cup.runtime.Symbol current) {
	
		//unrecovered_syntax_error(current);
		String messageExpected = "Syntax Error. Current symbol: '"+
			(current.value==null? gettokenstr(current.sym) : current.value) +
		    "'. Expected: ";
		
		int state = ((Symbol)stack.peek()).parse_state;
		short[] row = action_tab[state];
		
		for( int i = 0; i<row.length; i++)
		{
		   if( row[i]>0)
		   {
           		messageExpected += gettokenstr( row[i] ); i++;
		   }
		}
		logger.debug("syntax_error called");
		logger.debug(messageExpected);
		if (current instanceof ComplexSymbol) {
			ComplexSymbol cs = (ComplexSymbol) current;
			logger.debug("Left location:" + cs.getLeft());
			logger.debug("Right location:" + cs.getRight());
		}
		
		PepaLexer pl = (PepaLexer)this.getScanner();
		parserException = new ParserException( 
			pl.getCurrentChar(),
		    (pl.getCurrentLineNumber()+1),
		     pl.getCurrentColumn(), 
                     pl.yylength(),
		    messageExpected);
	}
	
  public void report_error(String message, java_cup.runtime.Symbol info){
		logger.debug("report_error called");
  }

        /** Fetches column and line number from the lexer, and then throws 
         *  an excpetion containing the error message to signal
         *  that parsing has been unsuccesful. If the symbol
         *  contains a value, this is also reported.
         */
	public void unrecovered_syntax_error(java_cup.runtime.Symbol Current) {
		logger.debug("unrecovered_syntax_error called");
		errorRecovered();
		//done_parsing();
		
	}

  public void report_fatal_error(String message, Object info) {
		logger.debug("report_fatal_error called");
  }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$PepaParser$actions {


	
	/* The top-level AST node for the parsed file */
	public ModelNode model = ASTFactory.createModel();
	
	/* Utility field for collecting temporary action sets */
	final ActionManager actionManager = new ActionManager();
	
	
	class ActionManager {
		
		private final Actions actions = new Actions();
		
		public ActionManager() {
			resetActions();
		}
		
		public void resetActions() {
			actions.clear();
		} 
		
		public void add(ActionTypeNode action) {
			actions.add(action);
		}
		
		public Actions get() {
			Actions copy = new Actions();
			copy.addAll(actions);
			resetActions();
			return copy;
		}
	}

  private final PepaParser parser;

  /** Constructor */
  CUP$PepaParser$actions(PepaParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$PepaParser$do_action(
    int                        CUP$PepaParser$act_num,
    java_cup.runtime.lr_parser CUP$PepaParser$parser,
    java.util.Stack            CUP$PepaParser$stack,
    int                        CUP$PepaParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$PepaParser$result;

      /* select the action based on the action number */
      switch (CUP$PepaParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // activity_action_type ::= TAU 
            {
              ActionSuperNode RESULT =null;
		 UnknownActionTypeNode action = ASTFactory.createUnknownActionType();
		                  	 RESULT = action;
		                  
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("activity_action_type",10, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // activity_action_type ::= action_type 
            {
              ActionSuperNode RESULT =null;
		int namedActionleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int namedActionright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		ActionTypeNode namedAction = (ActionTypeNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 RESULT = namedAction; 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("activity_action_type",10, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // action_type ::= QUOTED_STRN 
            {
              ActionTypeNode RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 	ActionTypeNode action = ASTFactory.createActionType();
		                  		action.setType(a);
		                  		RESULT = action; 
		                  
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("action_type",11, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // action_type ::= ACTIVITY_STRN 
            {
              ActionTypeNode RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 	ActionTypeNode action = ASTFactory.createActionType();
		                  		action.setType(a);
		                  		RESULT = action; 
		                  
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("action_type",11, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // action_list ::= 
            {
              RateDefinitionNode RESULT =null;
		 actionManager.resetActions(); 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("action_list",18, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // action_list ::= action_type 
            {
              RateDefinitionNode RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		ActionTypeNode type = (ActionTypeNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 actionManager.resetActions();
						  	   actionManager.add(type);
						  	
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("action_list",18, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // action_list ::= action_list COMMA action_type 
            {
              RateDefinitionNode RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).right;
		RateDefinitionNode list = (RateDefinitionNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		ActionTypeNode type = (ActionTypeNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 actionManager.add(type);
							
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("action_list",18, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // action_set ::= PAR 
            {
              Actions RESULT =null;
		 RESULT = actionManager.get(); 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("action_set",13, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // action_set ::= LCOOP action_list RCOOP 
            {
              Actions RESULT =null;
		 RESULT = actionManager.get(); 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("action_set",13, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // cooperation ::= process action_set process 
            {
              CooperationNode RESULT =null;
		int lhsleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).left;
		int lhsright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).right;
		ProcessNode lhs = (ProcessNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).value;
		int setleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).left;
		int setright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).right;
		Actions set = (Actions)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).value;
		int rhsleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int rhsright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		ProcessNode rhs = (ProcessNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		  CooperationNode coop = ASTFactory.createCooperation();
								coop.setLeft(lhs);
								coop.setRight(rhs);
								coop.setActionSet(set);
								RESULT = coop; 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("cooperation",3, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // wildcard_cooperation ::= process LCOOP MULT RCOOP process 
            {
              WildcardCooperationNode RESULT =null;
		int lhsleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-4)).left;
		int lhsright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-4)).right;
		ProcessNode lhs = (ProcessNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-4)).value;
		int rhsleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int rhsright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		ProcessNode rhs = (ProcessNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
			WildcardCooperationNode coop = ASTFactory.createWildcardCooperation();
								coop.setLeft(lhs);
								coop.setRight(rhs);
								RESULT = coop; 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("wildcard_cooperation",4, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-4)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // constant ::= QUOTED_STRN 
            {
              ConstantProcessNode RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 ConstantProcessNode constant = ASTFactory.createConstant();
			              	 	constant.setName(p);
			              	 	RESULT = constant; 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("constant",2, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // constant ::= PROCESS_STRN 
            {
              ConstantProcessNode RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 ConstantProcessNode constant = ASTFactory.createConstant();
			              		constant.setName(p);
								RESULT = constant; 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("constant",2, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // aggregation ::= constant LSQUARE finite_rate RSQUARE 
            {
              AggregationNode RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-3)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-3)).right;
		ConstantProcessNode p = (ConstantProcessNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-3)).value;
		int expressionleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).left;
		int expressionright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).right;
		FiniteRateNode expression = (FiniteRateNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).value;
		  AggregationNode aggr = ASTFactory.createAggregation();
								aggr.setCopies(expression);
								aggr.setProcessNode(p);
								RESULT = aggr; 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("aggregation",5, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-3)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // process ::= aggregation 
            {
              ProcessNode RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		AggregationNode a = (AggregationNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 RESULT = a; 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("process",1, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // process ::= constant 
            {
              ProcessNode RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		ConstantProcessNode c = (ConstantProcessNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 RESULT = c; 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("process",1, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // process ::= LPAREN process RPAREN 
            {
              ProcessNode RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).right;
		ProcessNode p = (ProcessNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).value;
		 RESULT = p; 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("process",1, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // process ::= process DIVIDE action_set 
            {
              ProcessNode RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).right;
		ProcessNode p = (ProcessNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		Actions l = (Actions)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 HidingNode hiding = ASTFactory.createHiding();
			                	hiding.setProcess(p);
			                	hiding.setActionSet(l);
			                	RESULT = hiding;
			                
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("process",1, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // process ::= cooperation 
            {
              ProcessNode RESULT =null;
		int coopleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int coopright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		CooperationNode coop = (CooperationNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 RESULT = coop; 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("process",1, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // process ::= wildcard_cooperation 
            {
              ProcessNode RESULT =null;
		int coopleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int coopright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		WildcardCooperationNode coop = (WildcardCooperationNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 RESULT = coop; 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("process",1, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // process ::= process SUM process 
            {
              ProcessNode RESULT =null;
		int p1left = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).left;
		int p1right = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).right;
		ProcessNode p1 = (ProcessNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).value;
		int p2left = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int p2right = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		ProcessNode p2 = (ProcessNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 ChoiceNode choice =ASTFactory.createChoice();
			                	choice.setLeft(p1);
			                	choice.setRight(p2);
			                	RESULT = choice;
			                
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("process",1, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // process ::= activity DOT process 
            {
              ProcessNode RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).right;
		ActivityNode a = (ActivityNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		ProcessNode p = (ProcessNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 PrefixNode prefix = ASTFactory.createPrefix();
			                	prefix.setActivity(a);
			                	prefix.setTarget(p);
			                	RESULT = prefix;
			                
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("process",1, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // passive_rate ::= TOP 
            {
              PassiveRateNode RESULT =null;
		 PassiveRateNode rate = ASTFactory.createPassiveRate();
								rate.setMultiplicity(1);
								RESULT = rate; 
							
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("passive_rate",8, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // passive_rate ::= PASSIVE_MULTIPLIER MULT TOP 
            {
              PassiveRateNode RESULT =null;
		int valueleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).right;
		Integer value = (Integer)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).value;
		  PassiveRateNode rate = ASTFactory.createPassiveRate();
								rate.setMultiplicity(value);
								RESULT = rate;
							
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("passive_rate",8, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // variable_rate ::= ACTIVITY_STRN 
            {
              VariableRateNode RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 VariableRateNode rate = ASTFactory.createRateVariable();
			                	rate.setName(name);
			                	RESULT = rate; 
			                
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("variable_rate",6, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // finite_rate ::= variable_rate 
            {
              FiniteRateNode RESULT =null;
		int rateleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int rateright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		VariableRateNode rate = (VariableRateNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 RESULT = rate; 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("finite_rate",9, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // finite_rate ::= PASSIVE_MULTIPLIER 
            {
              FiniteRateNode RESULT =null;
		int double_numberleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int double_numberright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		Integer double_number = (Integer)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 RateDoubleNode rate = ASTFactory.createRate();
			              		rate.setValue(double_number);
			              		RESULT = rate;
			              	
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("finite_rate",9, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // finite_rate ::= DOUBLE_NUMBER 
            {
              FiniteRateNode RESULT =null;
		int double_numberleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int double_numberright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		Double double_number = (Double)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 RateDoubleNode rate = ASTFactory.createRate();
			                	rate.setValue(double_number);
			                	RESULT = rate;
			                
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("finite_rate",9, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // finite_rate ::= LPAREN finite_rate RPAREN 
            {
              FiniteRateNode RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).right;
		FiniteRateNode r = (FiniteRateNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).value;
		 RESULT = r; 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("finite_rate",9, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // finite_rate ::= finite_rate DIVIDE finite_rate 
            {
              FiniteRateNode RESULT =null;
		int r1left = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).left;
		int r1right = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).right;
		FiniteRateNode r1 = (FiniteRateNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).value;
		int r2left = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int r2right = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		FiniteRateNode r2 = (FiniteRateNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		
			                 BinaryOperatorRateNode rate = 
   		                   	  	ASTFactory.createBinaryOperationRate();
   		                   	  rate.setLeft(r1);
   		                   	  rate.setRight(r2);
   		                   	  rate.setOperator(BinaryOperatorRateNode.Operator.DIV);
   		                   	  RESULT = rate; 
							 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("finite_rate",9, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // finite_rate ::= finite_rate MULT finite_rate 
            {
              FiniteRateNode RESULT =null;
		int r1left = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).left;
		int r1right = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).right;
		FiniteRateNode r1 = (FiniteRateNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).value;
		int r2left = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int r2right = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		FiniteRateNode r2 = (FiniteRateNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 
			                 BinaryOperatorRateNode rate = 
   		                   	  	ASTFactory.createBinaryOperationRate();
   		                   	  rate.setLeft(r1);
   		                   	  rate.setRight(r2);
   		                   	  rate.setOperator(BinaryOperatorRateNode.Operator.MULT);
   		                   	  RESULT = rate;
			                 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("finite_rate",9, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // finite_rate ::= finite_rate MINUS finite_rate 
            {
              FiniteRateNode RESULT =null;
		int r1left = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).left;
		int r1right = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).right;
		FiniteRateNode r1 = (FiniteRateNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).value;
		int r2left = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int r2right = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		FiniteRateNode r2 = (FiniteRateNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		
			                 BinaryOperatorRateNode rate = 
   		                   	  	ASTFactory.createBinaryOperationRate();
   		                   	  rate.setLeft(r1);
   		                   	  rate.setRight(r2);
   		                   	  rate.setOperator(BinaryOperatorRateNode.Operator.MINUS);
   		                   	  RESULT = rate;
			                 
			                
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("finite_rate",9, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // finite_rate ::= finite_rate SUM finite_rate 
            {
              FiniteRateNode RESULT =null;
		int r1left = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).left;
		int r1right = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).right;
		FiniteRateNode r1 = (FiniteRateNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)).value;
		int r2left = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int r2right = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		FiniteRateNode r2 = (FiniteRateNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 
   		                   	  BinaryOperatorRateNode rate = 
   		                   	  	ASTFactory.createBinaryOperationRate();
   		                   	  rate.setLeft(r1);
   		                   	  rate.setRight(r2);
   		                   	  rate.setOperator(BinaryOperatorRateNode.Operator.PLUS);
   		                   	  RESULT = rate;
   		                   
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("finite_rate",9, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // rate ::= passive_rate 
            {
              RateNode RESULT =null;
		int rateleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int rateright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		PassiveRateNode rate = (PassiveRateNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 RESULT = rate; 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("rate",7, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // rate ::= finite_rate 
            {
              RateNode RESULT =null;
		int rateleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int rateright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		FiniteRateNode rate = (FiniteRateNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 RESULT = rate; 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("rate",7, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // activity ::= LPAREN activity_action_type COMMA rate RPAREN 
            {
              ActivityNode RESULT =null;
		int actionleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-3)).left;
		int actionright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-3)).right;
		ActionSuperNode action = (ActionSuperNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-3)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).right;
		RateNode r = (RateNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).value;
		 ActivityNode act = ASTFactory.createActivity();
		                  	  act.setAction(action);
		                  	  act.setRate(r);
		                  	  RESULT = act;
		                  
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("activity",12, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-4)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // basic_process_definition ::= constant EQUALS process SEMI 
            {
              ProcessDefinitionNode RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-3)).right;
		ConstantProcessNode name = (ConstantProcessNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-3)).value;
		int resolvedleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).left;
		int resolvedright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).right;
		ProcessNode resolved = (ProcessNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).value;
		 	
                  				ProcessDefinitionNode procDef = 
                  					ASTFactory.createProcessDefinition();
                  				procDef.setName(name);
                  				procDef.setNode(resolved);
                  				model.processDefinitions().add(procDef);
                  				RESULT = procDef;
                  			 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("basic_process_definition",19, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-3)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // process_definition ::= basic_process_definition 
            {
              ProcessDefinitionNode RESULT =null;
		int defleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int defright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		ProcessDefinitionNode def = (ProcessDefinitionNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 RESULT = def; 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("process_definition",20, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // process_definition ::= HASH basic_process_definition 
            {
              ProcessDefinitionNode RESULT =null;
		int defleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int defright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		ProcessDefinitionNode def = (ProcessDefinitionNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 RESULT = def; 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("process_definition",20, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // basic_rate_definition ::= error SEMI 
            {
              RateDefinitionNode RESULT =null;
		
                          	 	/* Get the current token (SEMI) */
                          	 	//Symbol currentToken = parser.getStack().peek();
                          	 	this.parser.errorRecovered();
                          	 	
                          	 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("basic_rate_definition",15, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // basic_rate_definition ::= variable_rate rate_assignment_token finite_rate SEMI 
            {
              RateDefinitionNode RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-3)).right;
		VariableRateNode name = (VariableRateNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-3)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).right;
		FiniteRateNode r = (FiniteRateNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).value;
		 
                          	 	RateDefinitionNode rateDef = ASTFactory.createRateDefinition();
                          	 	rateDef.setName(name);
                          	 	rateDef.setRate(r);
                          	 	model.rateDefinitions().add(rateDef);
                          	 	RESULT = rateDef;                         	 		
                          	 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("basic_rate_definition",15, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-3)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // rate_definition ::= basic_rate_definition 
            {
              RateDefinitionNode RESULT =null;
		int rateleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int rateright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		RateDefinitionNode rate = (RateDefinitionNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		  //handleRateDefinitionError(rate);
						  		RESULT = rate; 
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("rate_definition",16, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // rate_definition ::= PERC basic_rate_definition 
            {
              RateDefinitionNode RESULT =null;
		int rateleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int rateright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		RateDefinitionNode rate = (RateDefinitionNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 //handleRateDefinitionError(rate);
							   RESULT = rate; 
							
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("rate_definition",16, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // rate_assignment_token ::= EQUALS 
            {
              Object RESULT =null;

              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("rate_assignment_token",14, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // rate_assignment_token ::= RATE_EQUALS 
            {
              Object RESULT =null;

              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("rate_assignment_token",14, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // process_definition_list ::= 
            {
              ProcessDefinitionNode RESULT =null;

              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("process_definition_list",21, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // process_definition_list ::= process_definition_list process_definition 
            {
              ProcessDefinitionNode RESULT =null;

              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("process_definition_list",21, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // rate_definition_list ::= 
            {
              RateDefinitionNode RESULT =null;

              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("rate_definition_list",17, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // rate_definition_list ::= rate_definition_list rate_definition 
            {
              RateDefinitionNode RESULT =null;

              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("rate_definition_list",17, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // model ::= rate_definition_list process_definition_list process 
            {
              ModelNode RESULT =null;
		int equationleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).left;
		int equationright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()).right;
		ProcessNode equation = (ProcessNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.peek()).value;
		 	model.setSystemEquation(equation);
	                       		RESULT = model;
	                        
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("model",0, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-2)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          return CUP$PepaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= model EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).right;
		ModelNode start_val = (ModelNode)((java_cup.runtime.Symbol) CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)).value;
		RESULT = start_val;
              CUP$PepaParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$PepaParser$stack.elementAt(CUP$PepaParser$top-1)), ((java_cup.runtime.Symbol)CUP$PepaParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$PepaParser$parser.done_parsing();
          return CUP$PepaParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

